### ISSUE TITLE
Default object isn't showing correctly

### ISSUE THREAD

**Issue by monpac** [alexandernst/angular-google-maps-geocoder#4]
i'm getting an [object Object] inside the input field with the default placeid.

![im](https://cloud.githubusercontent.com/assets/3440737/16400307/8e81f64c-3cb0-11e6-8549-6756fab09451.jpg)

**Comment by alexandernst** [comment]
Can you create a jsfiddle (or similar) so I can reproduce the problem, please?

**Comment by monpac** [comment]
Sorry, i left the error. I used the default javascript library of google maps. I'll make back the change so i can send the complete error.

**Comment by devheropl** [comment]
@monpac change line in js from          
`"typeahead='address for address in getLocation($viewValue)'" `
to
 `"uib-typeahead='address for address in getLocation($viewValue)'" +`
